apiVersion: v1
name: admission-webhook-server
version: 0.0.1
appVersion: 0.0.1
description: 
keywords:
- admission controller
- webhook
home: https://github.com/liangrog/admission-webhook-server
sources:
- https://github.com/liangrog/admission-webhook-server
engine: gotpl
